import { CareerTrack, SimulationInfo, ExpinarEvent, UserProfile } from "@cdp/types";

export const MOCK_USER: UserProfile = {
  id: "usr_demo_01",
  email: "alex.hunter@fintree.dev",
  fullName: "Alex Hunter",
  role: "student",
  xp: 1450,
  level: 4,
  activeTrackId: "track-equity",
  joinedAt: "2025-01-15",
};

export const MOCK_TRACKS: CareerTrack[] = [
  {
    id: "track-equity",
    title: "Equity Research Analyst",
    subtitle: "Financial modeling, valuation & quarterly earnings teardowns",
    description: "Master DCF valuations, three-statement modeling, and equity research report authoring through real-world corporate data simulations.",
    difficulty: "Intermediate",
    durationHours: 32,
    tags: ["Valuation", "DCF", "Financial Modeling", "Excel"],
    totalSimulations: 8,
    enrolledCount: 2420,
    badge: "Most Popular",
  },
  {
    id: "track-venture",
    title: "Venture Capital Associate",
    subtitle: "Cap tables, term sheets & startup due diligence",
    description: "Analyze seed & Series A decks, evaluate SaaS unit economics, negotiate liquidation preferences, and construct waterfall returns.",
    difficulty: "Advanced",
    durationHours: 28,
    tags: ["Cap Tables", "Due Diligence", "SaaS Metrics", "Term Sheets"],
    totalSimulations: 6,
    enrolledCount: 1840,
    badge: "High Impact",
  },
  {
    id: "track-pw",
    title: "Private Wealth & Portfolio Manager",
    subtitle: "Multi-asset allocation, risk hedging & client advisory",
    description: "Design tax-advantaged portfolios, stress-test macroeconomic drawdown scenarios, and conduct simulated high-net-worth client pitch sessions.",
    difficulty: "Intermediate",
    durationHours: 24,
    tags: ["Asset Allocation", "Fixed Income", "Risk Hedging", "HNW Advisory"],
    totalSimulations: 5,
    enrolledCount: 1190,
    badge: "Trending",
  },
  {
    id: "track-ib",
    title: "Investment Banking Analyst",
    subtitle: "M&A accretion/dilution, LBOs & deal pitching",
    description: "Build leveraged buyout models, evaluate leveraged loans & debt tranches, and construct pitch decks for mega-cap buyouts.",
    difficulty: "Advanced",
    durationHours: 40,
    tags: ["M&A", "LBO", "Leveraged Finance", "Comps"],
    totalSimulations: 10,
    enrolledCount: 3100,
    badge: "Intensive",
  },
];

export const MOCK_SIMULATIONS: SimulationInfo[] = [
  {
    id: "sim-1",
    slug: "equity-q3-apple",
    title: "Apple Inc. Q3 Earnings Teardown",
    trackId: "track-equity",
    difficulty: "Intermediate",
    durationMins: 45,
    xpReward: 350,
    description: "Stress-test supply chain disruption and calculate revised consensus EPS target using real 10-Q figures.",
    status: "in_progress",
    score: 82,
  },
  {
    id: "sim-2",
    slug: "venture-fintech-seed",
    title: "Fintech Seed Round Term Sheet Negotiation",
    trackId: "track-venture",
    difficulty: "Advanced",
    durationMins: 60,
    xpReward: 500,
    description: "Evaluate founder equity dilution, anti-dilution clauses, and board veto rights across 3 counter-offers.",
    status: "available",
  },
  {
    id: "sim-3",
    slug: "pw-macro-crisis",
    title: "2026 Rate Cut & Inflation Hedge Strategy",
    trackId: "track-pw",
    difficulty: "Beginner",
    durationMins: 30,
    xpReward: 250,
    description: "Rebalance a $10M portfolio amidst central bank surprise announcements to maximize risk-adjusted Sharpe ratio.",
    status: "available",
  },
  {
    id: "sim-4",
    slug: "equity-dcf-basics",
    title: "Three-Statement Integration Fundamentals",
    trackId: "track-equity",
    difficulty: "Beginner",
    durationMins: 30,
    xpReward: 200,
    description: "Dynamically link Income Statement to Balance Sheet & Cash Flow under working capital shifts.",
    status: "completed",
    score: 95,
  },
];

export const MOCK_EXPINARS: ExpinarEvent[] = [
  {
    id: "exp-1",
    title: "Inside Goldman Sachs M&A: Live Pitch Deconstruction",
    speaker: "Vikram Malhotra",
    speakerRole: "Managing Director, Global TMT Banking",
    scheduledTime: "Today at 7:00 PM IST",
    attendeeCount: 1420,
    status: "live",
    category: "M&A Masterclass",
  },
  {
    id: "exp-2",
    title: "How Top Tier VCs Spot $10B Companies at Seed",
    speaker: "Pooja Singhania",
    speakerRole: "Partner, Matrix Partners",
    scheduledTime: "Tomorrow at 6:30 PM IST",
    attendeeCount: 980,
    status: "upcoming",
    category: "Venture Capital",
  },
];
